"""Object storage abstraction (Adapter pattern).

Callers depend only on ``ObjectStorage``: a small, key-based interface shaped
like S3/GCS/Azure Blob. ``LocalDiskStorage`` implements it on the local
filesystem for this demo; a production ``S3Storage`` would implement the same
methods with boto3 and nothing that calls it would change.
"""

from __future__ import annotations

import os
import re
import uuid
from contextlib import AbstractContextManager, contextmanager
from pathlib import Path
from typing import BinaryIO, Iterator, Protocol, runtime_checkable

COPY_BUFFER_BYTES = 1024 * 1024  # 1 MiB
# Conservative key alphabet: what S3 treats as "safe characters", plus "/"
# as a prefix separator. Keys are generated by the app (from job ids), never
# taken verbatim from user input, so this only ever rejects bugs and attacks.
_KEY_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)*$")


class StorageError(Exception):
    # Stable codes, recorded on the job row when a storage fault fails a job.
    error_code = "storage_error"


class InvalidKeyError(StorageError, ValueError):
    error_code = "invalid_storage_key"


class ObjectNotFoundError(StorageError, FileNotFoundError):
    error_code = "audio_not_found"


class ObjectTooLargeError(StorageError):
    error_code = "file_too_large"

    def __init__(self, max_bytes: int) -> None:
        super().__init__(f"Object exceeds the {max_bytes}-byte limit")
        self.max_bytes = max_bytes


@runtime_checkable
class ObjectStorage(Protocol):
    def save(self, key: str, source: BinaryIO, max_bytes: int | None = None) -> int:
        """Stream ``source`` into ``key``; return bytes written.

        Raises ``ObjectTooLargeError`` (and stores nothing) if the stream
        exceeds ``max_bytes``.
        """
        ...

    def open(self, key: str) -> BinaryIO:
        """Open an object for binary reading."""
        ...

    def as_local_file(self, key: str) -> AbstractContextManager[Path]:
        """Context manager yielding a local filesystem path for ``key``.

        Tools like ffmpeg need a real file. Local disk yields the file in
        place; a remote store would download to a temp file and delete it on
        exit.
        """
        ...

    def exists(self, key: str) -> bool: ...

    def delete(self, key: str) -> None:
        """Delete ``key``; deleting a missing key is not an error (like S3)."""
        ...

    def presigned_upload_url(self, key: str, expires_seconds: int = 900) -> str:
        """A URL the client can upload to directly, bypassing the API process.

        This is the seam for large-file uploads in production (S3 presigned
        PUT). Stores that can't support it raise ``NotImplementedError``.
        """
        ...


class LocalDiskStorage:
    """``ObjectStorage`` on a local directory; keys map to relative paths."""

    def __init__(self, root: str | Path) -> None:
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def _path_for(self, key: str) -> Path:
        if not isinstance(key, str) or not _KEY_PATTERN.fullmatch(key) or ".." in key.split("/"):
            raise InvalidKeyError(f"Invalid storage key: {key!r}")
        path = (self.root / key).resolve()
        # Belt and braces: even a key that passes the pattern must not escape
        # the root (e.g. via a symlink inside it).
        if not path.is_relative_to(self.root):
            raise InvalidKeyError(f"Storage key escapes the storage root: {key!r}")
        return path

    def save(self, key: str, source: BinaryIO, max_bytes: int | None = None) -> int:
        path = self._path_for(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        # Write to a temp name and rename into place, so a reader never sees a
        # partial object and a failed/oversized upload leaves nothing behind.
        tmp = path.with_name(f".{path.name}.{uuid.uuid4().hex}.part")
        written = 0
        try:
            with open(tmp, "wb") as out:
                while chunk := source.read(COPY_BUFFER_BYTES):
                    written += len(chunk)
                    if max_bytes is not None and written > max_bytes:
                        raise ObjectTooLargeError(max_bytes)
                    out.write(chunk)
            os.replace(tmp, path)
        except BaseException:
            tmp.unlink(missing_ok=True)
            raise
        return written

    def open(self, key: str) -> BinaryIO:
        path = self._path_for(key)
        try:
            return open(path, "rb")
        except FileNotFoundError as exc:
            raise ObjectNotFoundError(f"No such object: {key}") from exc

    @contextmanager
    def as_local_file(self, key: str) -> Iterator[Path]:
        path = self._path_for(key)
        if not path.is_file():
            raise ObjectNotFoundError(f"No such object: {key}")
        yield path

    def exists(self, key: str) -> bool:
        return self._path_for(key).is_file()

    def delete(self, key: str) -> None:
        self._path_for(key).unlink(missing_ok=True)

    def presigned_upload_url(self, key: str, expires_seconds: int = 900) -> str:
        self._path_for(key)  # validate the key the same way a real store would
        raise NotImplementedError(
            "Local disk storage can't issue presigned URLs; uploads go through "
            "the API. An S3-backed ObjectStorage would return a presigned PUT URL."
        )
